### ISSUE TITLE
How to install this package ?

### ISSUE THREAD

**Issue by meftunca** [ArchireportTeam/react-native-svg-draw#1]
`npm install @archireport/react-native-svg-draw ` 
It is not working

**Comment by mlecoq** [comment]
@meftunca I didn't see that package was private. Thanks for pointing it up !

**Comment by meftunca** [comment]
If you have a roadmap for the project, I can support

**Comment by mlecoq** [comment]
> If you have a roadmap for the project, I can support

I’ll make one !
