### ISSUE TITLE
JSON value 'hsl(0%,100%, 3.5527136e-14)' of type NSString cannot be converted to a UIColor. Did you forget to call processColor() on the JS side? 

### ISSUE THREAD

**Issue by bibesh07** [ArchireportTeam/react-native-svg-draw#10]
Issue arises when sliding the slider all the way to the bottom on DrawWithOptions color slider on iOS. 

Temporary solution is to update the onGestureEvent on ColorSlider.tsx and round down the color value to 10 digits.

 color.value = `hsl(${0 as number}, ${100 as number}%, ${Math.max(
            50 -
            ((slidePos - 0.9 * sliderHeight.value) /
              (0.1 * sliderHeight.value)) *
            50,
            0
          ).toFixed(10)}%)` as const;

**Comment by mlecoq** [comment]
Thanks for your issue, you're right I will do this
