### ISSUE TITLE
1.2.0 version android not work but ios work normal

### ISSUE THREAD

**Issue by yellowstrong** [ArchireportTeam/react-native-svg-draw#16]
It is found in the test that the project depends on the version of the react native svg. It needs to reduce the react native svg to 12.1.0 to work normally. It is hoped that the developers can synchronously upgrade the relevant plug-in versions they depend on later！thanks。

**Comment by mlecoq** [comment]
Yes there are some issues with react-native-svg 13.x (some are fixed) and code needs to be updated (especially concerning animation with reanimated). I will do it soon
